name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install gettext
      run: sudo apt install gettext
    - name: install libupnp-1.14
      run: wget https://github.com/pupnp/pupnp/releases/download/release-1.14.0/libupnp-1.14.0.tar.bz2 && tar xjvf libupnp-1.14.0.tar.bz2 && cd libupnp-1.14.0 && ./configure --disable-nls && sudo make install && cd ..
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make dist
      run: make dist
