name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-install
      run: sudo apt install libupnp-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make dist
      run: make dist
